### ISSUE TITLE
SSL issue with Confluent Schema Registry

### ISSUE THREAD

**Issue by javigoncompte** [datastax/kafka-sink#132]
Can't read from topics or deserialize topics due to SSL connection issues between connector and confluent schema registry. Our custom kafka -> cassandra consumer works using SSL. We are using jks type certificates
 
`Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

`Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic bookings to Avro:
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:107)
        at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertKey(WorkerSinkTask.java:530)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:493)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
        ... 13 more
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 13`

**Comment by OneCricketeer** [comment]
Hello. I'm not sure this issue is related to the Cassandra connector since the Schema Registry deserialization process happens before data arrives to a specific connector task.

Please open an issue with the Confluent Schema Registry github project
